### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by paskal**
Hi @rigobauer, and thank you a lot for your module!

It's really cool to use and I can confirm it works with the latest `abcjs`, however, it's hard to tell it because it's tied up to `3.x.x` version instead of the current `5.12.0`. This PR bumps `abcjs`, as well as all other dependencies.

Please let me know if I changed too many packages, and I'll revert the change to whatever you want up to only `abcjs`: this one is crucial.

### CODE REVIEW

**Comment by rigobauer** [comment]
Hi Dmitry!
Thanks a lot for this! It's been in my "to do" list for a long time, but work has been keeping me away from this road.
I'm going to directly trust you on this, because you probably have more experience with it than me right now ;)

**Comment by paskal** [comment]
@rigobauer would you be so kind as to release new version of the package to [npmjs](https://www.npmjs.com/package/react-abcjs)?

**Comment by rigobauer** [comment]
> @rigobauer would you be so kind as to release new version of the package to [npmjs](https://www.npmjs.com/package/react-abcjs)?

You got it! Sorry for the delay, but I haven't touch this in a while and I had to remember how it works! :)

**Pull request merged**
